"use client";

import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import {
  AlertCircle,
  CheckCircle2,
  ChevronRight,
  Code2,
  Database,
  Terminal,
  GitPullRequest,
  Activity,
  Download,
} from "lucide-react";

const STAGES = [
  { id: "detecting", label: "Detecting" },
  { id: "aggregating", label: "Coral Aggregation" },
  { id: "diagnosing", label: "AI Diagnosis" },
  { id: "sandboxing", label: "Sandboxing" },
  { id: "pending_approval", label: "Human Gate" },
  { id: "healing", label: "Executing" },
  { id: "healed", label: "Healed" },
];

export default function WarRoom() {
  const searchParams = useSearchParams();
  const targetId = searchParams.get("id");

  const [incident, setIncident] = useState<any>(null);
  const [isPolling, setIsPolling] = useState(true);

  // --- LIVE BACKEND CONNECTION & ROUTING ---
  useEffect(() => {
    const fetchIncident = async () => {
      try {
        let url = "http://127.0.0.1:8080/api/incidents";
        if (targetId) {
          url = `http://127.0.0.1:8080/api/state?id=${targetId}`;
        }

        const res = await fetch(url);
        if (!res.ok) return;
        const data = await res.json();

        if (targetId) {
          setIncident(data);
        } else if (data && data.length > 0) {
          const sorted = data.sort(
            (a: any, b: any) =>
              new Date(b.created_at).getTime() -
              new Date(a.created_at).getTime(),
          );
          setIncident(sorted[0]);
        }
      } catch (err) {
        // Silent catch
      }
    };

    if (isPolling) {
      fetchIncident();
      const interval = setInterval(fetchIncident, 1500);
      return () => clearInterval(interval);
    }
  }, [isPolling, targetId]);

  const approveFix = async () => {
    if (!incident) return;
    try {
      setIncident((prev: any) => ({ ...prev, stage: "healing" }));
      await fetch("http://127.0.0.1:8080/api/approve", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: incident.id }),
      });
    } catch (e) {
      console.error("Failed to approve fix:", e);
    }
  };

  const downloadPostMortem = () => {
    if (!incident) return;

    const markdown = `# 🚨 Incident Post-Mortem: ${incident.id}
**Date:** ${new Date().toLocaleDateString()}
**Repository:** ${incident.repo}
**Commit SHA:** \`${incident.head_sha}\`
**Status:** ✅ RESOLVED

---

## 📋 Incident Summary
The CI/CD pipeline failed. Engram Autonomous SRE intercepted the failure, analyzed the logs, and successfully applied a patch without human engineering intervention.

### Failed Jobs
\`\`\`text
${incident.failed_jobs?.trim() || "N/A"}
\`\`\`

## 🧠 Root Cause Analysis (AI Diagnosis)
Based on the execution logs and repository state, the root cause was identified as:
> ${incident.diagnosis_summary || "Engram AI identified a configuration or logic fault."}

## 💥 Blast Radius (Coral Telemetry)
The following commit data was aggregated to assess the blast radius:
\`\`\`json
${incident.commit_context || "No recent commit data correlated."}
\`\`\`

## 🛠️ Remediation & Fix
Engram generated the following patch with a confidence score of **${incident.confidence_score}%**. The fix was approved and pushed to the repository.

### Applied Git Diff
\`\`\`diff
${incident.generated_diff || "No diff available."}
\`\`\`

---
*Auto-generated by Engram SRE Mission Control*
`;

    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `post-mortem-${incident.id}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // --- RENDER STANDBY STATE ---
  if (!incident) {
    return (
      <div className="max-w-[1080px] mx-auto px-6 sm:px-12 py-32 text-center animate-in fade-in zoom-in duration-500 font-sans">
        <div className="w-16 h-16 bg-[#f7f7f5] border border-[#e9e9e7] rounded-xl flex items-center justify-center mx-auto mb-6">
          <Activity
            className="w-8 h-8 text-[#0f7b6c] animate-pulse"
            strokeWidth={1.5}
          />
        </div>
        <h1 className="text-[28px] font-bold text-[#37352f] mb-3 tracking-tight">
          War Room Standby
        </h1>
        <p className="text-[#787774] text-[15px] mb-8 max-w-md mx-auto">
          Connection established. Listening to Go Backend on{" "}
          <code className="bg-[#f1f1ef] px-1.5 py-0.5 rounded text-[13px] font-mono text-[#eb5757]">
            localhost:8080
          </code>{" "}
          for incoming webhook failures.
        </p>
      </div>
    );
  }

  // --- RENDER ACTIVE STATE ---
  return (
    <div className="max-w-[1080px] mx-auto px-6 sm:px-12 py-8 sm:py-12 pb-24 font-sans animate-in fade-in duration-300">
      {/* HEADER */}
      <header className="mb-10 flex flex-col sm:flex-row sm:items-start justify-between gap-4">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <span className="text-[32px] leading-none">🚨</span>
            <h1 className="text-[32px] leading-tight font-bold tracking-tight text-[#c1292e]">
              Active Incident
            </h1>
            <span className="bg-[#fce8e6] text-[#c1292e] border border-[#f5c6cb] px-2 py-0.5 rounded text-[11px] font-bold tracking-wider uppercase ml-2 mt-1.5">
              {incident.id}
            </span>
          </div>
          <p className="text-[#787774] text-[14px] mt-2 sm:ml-12 flex items-center flex-wrap gap-2">
            Target:
            <span className="font-mono text-[#37352f] bg-[#f7f7f5] border border-[#e9e9e7] px-1.5 py-0.5 rounded text-[12px]">
              {incident.repo}
            </span>
            on commit
            <span className="font-mono text-[#37352f] bg-[#f7f7f5] border border-[#e9e9e7] px-1.5 py-0.5 rounded text-[12px]">
              {incident.head_sha?.substring(0, 7)}
            </span>
          </p>
        </div>

        <div className="flex items-center mt-2 sm:mt-0">
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-md bg-white border border-[#e9e9e7]">
            <div className="w-2 h-2 rounded-full bg-[#0f7b6c] animate-pulse" />
            <span className="text-xs font-medium text-[#37352f]">
              Live Connection
            </span>
          </div>
        </div>
      </header>

      {/* 6-STAGE PIPELINE TRACKER */}
      <div className="bg-white border border-[#e9e9e7] rounded-lg p-6 mb-10 overflow-x-auto">
        <div className="flex items-center justify-between min-w-[700px]">
          {STAGES.map((stage, idx) => {
            const isActive = incident.stage === stage.id;
            const isPast =
              STAGES.findIndex((s) => s.id === incident.stage) > idx;

            return (
              <div key={stage.id} className="flex items-center flex-1">
                <div
                  className={`flex flex-col items-center gap-2.5 w-full ${isActive || isPast ? "opacity-100" : "opacity-40"}`}
                >
                  <div
                    className={`w-7 h-7 rounded-full flex items-center justify-center text-[12px] font-semibold border transition-all duration-300
                    ${
                      isPast
                        ? "bg-[#37352f] border-[#37352f] text-white"
                        : isActive && stage.id === "pending_approval"
                          ? "bg-[#fdf3c0] border-[#e2b719] text-[#6b4a0d] animate-pulse"
                          : isActive
                            ? "bg-[#eaf3fc] border-[#2383e2] text-[#2383e2]"
                            : "bg-[#fbfbfa] border-[#e9e9e7] text-[#9b9a97]"
                    }`}
                  >
                    {isPast ? (
                      <CheckCircle2 className="w-4 h-4" strokeWidth={2.5} />
                    ) : (
                      idx + 1
                    )}
                  </div>
                  <span
                    className={`text-[11px] font-medium tracking-wide text-center ${
                      isActive ? "text-[#37352f]" : "text-[#787774]"
                    }`}
                  >
                    {stage.label}
                  </span>
                </div>
                {idx < STAGES.length - 1 && (
                  <div
                    className={`flex-1 h-px mx-2 transition-colors ${
                      isPast ? "bg-[#37352f]" : "bg-[#e9e9e7]"
                    }`}
                  />
                )}
              </div>
            );
          })}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* LEFT COLUMN: Data Aggregation */}
        <div className="space-y-8 flex flex-col">
          {/* Terminal Stream */}
          <section>
            <h3 className="text-[15px] font-semibold text-[#37352f] mb-3 border-b border-[#e9e9e7] pb-2 flex items-center gap-2">
              <Terminal className="w-4 h-4 text-[#787774]" strokeWidth={1.5} />{" "}
              Failing Jobs Context
            </h3>
            <div className="bg-[#f7f7f5] rounded-md p-4 font-mono text-[12px] text-[#eb5757] overflow-y-auto h-[180px] border border-[#e9e9e7]">
              {incident.failed_jobs ? (
                <pre className="whitespace-pre-wrap leading-relaxed">
                  {incident.failed_jobs}
                </pre>
              ) : (
                <span className="text-[#9b9a97] italic">
                  Waiting for CI telemetry...
                </span>
              )}
            </div>
          </section>

          {/* Coral Data & Blast Radius */}
          <section className="flex-grow">
            <h3 className="text-[15px] font-semibold text-[#37352f] mb-3 border-b border-[#e9e9e7] pb-2 flex items-center gap-2">
              <Database className="w-4 h-4 text-[#787774]" strokeWidth={1.5} />{" "}
              Coral Graph Data
            </h3>

            <div className="mb-5">
              <span className="text-[11px] font-semibold text-[#787774] mb-1.5 block">
                Executed Query
              </span>
              <div className="bg-[#f7f7f5] rounded-md p-3 font-mono text-[12px] text-[#37352f] overflow-x-auto border border-[#e9e9e7]">
                {incident.coral_sql_query ? (
                  <pre>{incident.coral_sql_query}</pre>
                ) : (
                  <span className="text-[#9b9a97] italic">
                    Awaiting SQL execution...
                  </span>
                )}
              </div>
            </div>

            <div>
              <span className="text-[11px] font-semibold text-[#787774] mb-1.5 block">
                Blast Radius / Commit Context
              </span>
              <div className="bg-[#f7f7f5] rounded-md p-3 font-mono text-[12px] text-[#37352f] overflow-y-auto max-h-[140px] border border-[#e9e9e7]">
                {incident.commit_context ? (
                  <pre className="whitespace-pre-wrap">
                    {incident.commit_context}
                  </pre>
                ) : (
                  <span className="text-[#9b9a97] italic">
                    Awaiting data aggregation...
                  </span>
                )}
              </div>
            </div>
          </section>
        </div>

        {/* RIGHT COLUMN: AI & Actions */}
        <div className="space-y-8 flex flex-col">
          {/* AI Sandboxing / Git Diff View */}
          <section className="flex-grow flex flex-col">
            <div className="flex items-center justify-between mb-3 border-b border-[#e9e9e7] pb-2">
              <h3 className="text-[15px] font-semibold text-[#37352f] flex items-center gap-2">
                <Code2 className="w-4 h-4 text-[#787774]" strokeWidth={1.5} />{" "}
                Generated Git Diff
              </h3>
              {incident.confidence_score > 0 && (
                <span className="bg-[#eaf3fc] text-[#2383e2] px-2 py-0.5 rounded text-[11px] font-semibold">
                  Confidence: {incident.confidence_score}%
                </span>
              )}
            </div>

            <div className="bg-[#fbfbfa] rounded-md p-4 font-mono text-[12px] overflow-x-auto overflow-y-auto h-[320px] border border-[#e9e9e7] flex-grow">
              {incident.generated_diff ? (
                <pre className="whitespace-pre-wrap break-words leading-[1.6]">
                  {incident.generated_diff
                    .split("\n")
                    .map((line: string, i: number) => {
                      const isAdded =
                        line.startsWith("+") && !line.startsWith("+++");
                      const isRemoved =
                        line.startsWith("-") && !line.startsWith("---");
                      const lineClass = isAdded
                        ? "bg-[#e6f4ea] text-[#1e4620]"
                        : isRemoved
                          ? "bg-[#fce8e6] text-[#c1292e]"
                          : "text-[#37352f]";

                      return (
                        <div key={i} className={`${lineClass} px-1 rounded-sm`}>
                          {line}
                        </div>
                      );
                    })}
                </pre>
              ) : (
                <div className="flex items-center justify-center h-full text-[#9b9a97] italic">
                  Waiting for Gemini to generate diff...
                </div>
              )}
            </div>
          </section>

          {/* THE HUMAN GATE */}
          {incident.stage === "pending_approval" && (
            <div className="bg-[#fdf3c0] border border-[#fae29c] rounded-lg p-5 animate-in fade-in zoom-in-95 duration-300">
              <div className="flex items-start gap-4">
                <AlertCircle
                  className="w-5 h-5 text-[#dfab01] flex-shrink-0 mt-0.5"
                  strokeWidth={2}
                />
                <div className="w-full">
                  <h4 className="font-semibold text-[#402c1b] mb-1">
                    Human Authorization Required
                  </h4>
                  <p className="text-[13px] text-[#6b4a0d] mb-4">
                    Sandbox validation passed. Review the generated diff above
                    and authorize to apply the fix.
                  </p>
                  <button
                    onClick={approveFix}
                    className="w-full bg-[#402c1b] hover:bg-[#2c1e13] text-white text-[13px] font-medium py-2.5 rounded shadow-sm transition-colors flex items-center justify-center gap-2"
                  >
                    Approve & Deploy Fix <ChevronRight className="w-4 h-4" />
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Healing State */}
          {incident.stage === "healing" && (
            <div className="bg-[#f7f7f5] border border-[#e9e9e7] rounded-lg p-6 text-center animate-in fade-in duration-300">
              <div className="animate-spin w-5 h-5 border-[2px] border-[#37352f] border-t-transparent rounded-full mx-auto mb-3" />
              <h4 className="font-semibold text-[#37352f] text-[14px]">
                Applying Remediation
              </h4>
              <p className="text-[13px] text-[#787774] mt-1">
                Committing changes and pushing fix branch...
              </p>
            </div>
          )}

          {/* Healed State + Post Mortem Button */}
          {incident.stage === "healed" && (
            <div className="bg-[#e6f4ea] border border-[#ceead6] rounded-lg p-6 text-center animate-in fade-in duration-500">
              <CheckCircle2
                className="w-8 h-8 text-[#1e4620] mx-auto mb-2"
                strokeWidth={1.5}
              />
              <h4 className="font-semibold text-[#1e4620] text-[15px]">
                System Healed
              </h4>
              <p className="text-[13px] text-[#1e4620]/80 mt-1 mb-5">
                Fix applied and Pull Request successfully opened.
              </p>

              <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
                {incident.pr_url && (
                  <a
                    href={incident.pr_url}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex items-center gap-1.5 bg-white text-[#1e4620] border border-[#ceead6] px-4 py-2 rounded font-medium text-[13px] hover:bg-[#f3f9f4] transition-colors"
                  >
                    <GitPullRequest className="w-4 h-4" strokeWidth={1.5} />{" "}
                    View Pull Request
                  </a>
                )}

                <button
                  onClick={downloadPostMortem}
                  className="inline-flex items-center gap-1.5 bg-[#1e4620] text-white px-4 py-2 rounded font-medium text-[13px] hover:bg-[#153216] transition-colors"
                >
                  <Download className="w-4 h-4" strokeWidth={1.5} /> Download
                  Post-Mortem
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
